export enum StatusEffects {
  BLINDED = 'blinded',
  CHARMED = 'charmed',
  DEAD = 'dead',
  DEAFENED = 'deafened',
  EXHAUSTION = 'exhaustion',
  FRIGHTENED = 'frightened',
  GRAPPLED = 'grappled',
  INCAPACITATED = 'incapacitated',
  INVISIBLE = 'invisible',
  PARALYZED = 'paralyzed',
  PETRIFIED = 'petriifed',
  POISONED = 'poisoned',
  PRONE = 'prone',
  RESTRAINED = 'restrained',
  STUNNED = 'stunned',
  UNCONSCIOUS = 'unconscious',
}